default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flashsale_development
  username: <%= Rails.application.secrets.username %>
  password: <%= Rails.application.secrets.password %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: flashsale_production
  username: postgres
  password: 1234
